server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12353890
    log-statement: true
  sql:
    init:
      mode: always
